version: "3.8"

services:
  # ─── MINIO (Local S3) ───────────────────────────
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - supplychain_network

    # ─── MINIO INIT (creates buckets on startup) ───
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: /bin/bash
    command: /init_buckets.sh
    volumes:
      - ./docker/minio/init_buckets.sh:/init_buckets.sh
    networks:
      - supplychain_network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB},${AIRFLOW_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/01_create_databases.sql:/docker-entrypoint-initdb.d/01_create_databases.sql
      - ./docker/postgres/02_create_tables.sql:/docker-entrypoint-initdb.d/02_create_tables.sql
    networks:
      - supplychain_network

  # ─── ZOOKEEPER (Kafka needs this) ───────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - supplychain_network

  # ─── KAFKA (Real-time streaming) ────────────────
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    platform: linux/amd64
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - supplychain_network

  # ─── AIRFLOW (webserver) ─────────────────────
  airflow-webserver:
    build: ./docker/airflow
    container_name: airflow-webserver
    ports:
      - "${AIRFLOW_PORT}:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${AIRFLOW_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    volumes:
      - ./orchestration/dags:/opt/airflow/dags
      - ./orchestration/logs:/opt/airflow/logs
      - ./ingestion:/opt/airflow/ingestion
      - ./processing:/opt/airflow/processing
      - ./quality:/opt/airflow/quality
    command: webserver
    networks:
      - supplychain_network

  # ─── AIRFLOW SCHEDULER ─────────────────────────
  airflow-scheduler:
    build: ./docker/airflow
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${AIRFLOW_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    depends_on:
      - postgres
    volumes:
      - ./orchestration/dags:/opt/airflow/dags
      - ./orchestration/logs:/opt/airflow/logs
      - ./ingestion:/opt/airflow/ingestion
      - ./processing:/opt/airflow/processing
      - ./quality:/opt/airflow/quality
    command: scheduler
    networks:
      - supplychain_network

  # ─── AIRFLOW INIT (runs once then exits) ───────
  airflow-init:
    build: ./docker/airflow
    container_name: airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${AIRFLOW_DB}
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin123 \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@admin.com
    networks:
      - supplychain_network

  # ─── PGADMIN (Postgres Browser UI) ─────────────
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - supplychain_network

# ─── VOLUMES (Persistent storage) ──────────────────
volumes:
  minio_data:
  postgres_data:

# ─── NETWORK (All tools talk to each other) ────────
networks:
  supplychain_network:
    driver: bridge
